#include <iostream>
using namespace std;

class Car {
private:
    string brand;
    string model;
    double rentalPrice;
    bool available;
    double revenue;

public:
    Car(string b,string m, double price)
        : brand(b), model(m), rentalPrice(price), available(true), revenue(0.0) {}
    void rentCar(int days) {
        if (!available) {
            cout << "Car is already rented.\n";
            return;
        }

        double totalPrice = rentalPrice * days;
        revenue += totalPrice;  
        available = false; 
        cout << "Car rented for " << days << " days. Total cost: Rs." << totalPrice << "\n";
    }
    void displayRevenue() {
        cout << "Total revenue generated by " << brand << " " << model << ": Rs." << revenue << "\n";
    }
    void display() {
        cout << "Brand: " << brand << ", Model: " << model<< ", Price per day: Rs." << rentalPrice << ", Available: "<< (available ? "Yes" : "No") << "\n";
    }
};
int main() {
    Car car1("Ford", "Focus", 70.0);
    car1.display();
    car1.rentCar(5);  
    car1.displayRevenue();
    car1.rentCar(3);  
    car1.displayRevenue();

    return 0;
}
